<a href="https://colab.research.google.com/github/FaustinoMuetunda/Algorithms-and-Data-Structures/blob/master/svc_mentalwll.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

%matplotlib inline


dataset=pd.read_csv ("dataSet.csv", sep = ';')

dataset.keys()

Index(['age', 'everused_alcohol', 'seen_pychaitrist', 'Depression', 'Anxiety',
       'Mental_Wellbeing', 'Somatic', 'NonSomatic_Somatic', 'Suicide'],
      dtype='object')

In [ ]:
y = dataset['Mental_Wellbeing']
X = dataset.drop(['Mental_Wellbeing'], axis=1)

In [ ]:
X

age  everused_alcohol  seen_pychaitrist  Depression  Anxiety  Somatic  \
0     19                 4                 4           2        2        1   
1     17                 4                 4           1        2        1   
2     15                 4                 1           1        0        1   
3     16                 3                 4           3        2        2   
4     16                 3                 3           0        0        0   
..   ...               ...               ...         ...      ...      ...   
548   16                 1                 1           4        2        2   
549   17                 1                 1           3        2        2   
550   17                 1                 1           4        2        2   
551   18                 1                 1           4        3        2   
552   20                 1                 1           4        1        3   

     NonSomatic_Somatic  Suicide  
0                     2        2  
1                     2        2  
2                     2        0  
3                     3        2  
4                     0        0  
..                  ...      ...  
548                   4        0  
549                   4        2  
550                   4        0  
551                   4        2  
552                   4        2  

[553 rows x 8 columns]

In [ ]:
y

0      2
1      1
2      3
3      1
4      3
      ..
548    2
549    2
550    1
551    0
552    3
Name: Mental_Wellbeing, Length: 553, dtype: int64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
from sklearn import model_selection
from sklearn.svm import SVC

model = SVC()

model.fit(X_train, y_train)

pred=model.predict(X_test)
model.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        14
           1       0.49      0.53      0.51        57
           2       0.33      0.06      0.10        35
           3       0.53      0.79      0.63        77

    accuracy                           0.51       183
   macro avg       0.34      0.34      0.31       183
weighted avg       0.44      0.51      0.44       183



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
param_grid={'C':[0.1, 1, 10, 100, 1000], 'gamma': [1,0,1, 0.01, 0.001, 0.0001], 'kernel':['rbf']}

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(SVC(), param_grid, refit=True, verbose=3)

In [ ]:
grid.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.338 total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.351 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.351 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.365 total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.365 total time=   0.0s
[CV 1/5] END ........C=0.1, gamma=0, kernel=rbf;, score=0.311 total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=0, kernel=rbf;, score=0.311 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=0, kernel=rbf;, score=0.311 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=0, kernel=rbf;, score=0.311 total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=0, kernel=rbf;, score=0.311 total time=   0.0s
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.338 total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0, 1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [ ]:
pred=grid.predict(X_test)

In [ ]:
print(classification_report(y_test,pred))
print('\n')
print(confusion_matrix(y_test, pred)) 

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        14
           1       0.49      0.49      0.49        57
           2       0.20      0.37      0.26        35
           3       0.61      0.48      0.54        77

    accuracy                           0.43       183
   macro avg       0.32      0.34      0.32       183
weighted avg       0.45      0.43      0.43       183



[[ 0  5  6  3]
 [ 0 28 18 11]
 [ 0 12 13 10]
 [ 0 12 28 37]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [ ]:
from sklearn import metrics
print(classification_report(y_test,y_pred))
print('\n')
print(confusion_matrix(y_test,y_pred)) 

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        14
           1       0.37      0.46      0.41        57
           2       0.26      0.23      0.24        35
           3       0.54      0.57      0.55        77

    accuracy                           0.43       183
   macro avg       0.29      0.31      0.30       183
weighted avg       0.39      0.43      0.41       183



[[ 0  8  1  5]
 [ 0 26 12 19]
 [ 0 13  8 14]
 [ 0 23 10 44]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
bagging = BaggingClassifier(KNeighborsClassifier(), max_samples=0.5, max_features=0.5)



In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
clf = RandomForestClassifier(n_estimators=10)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(classification_report(y_test,y_pred))
print('\n')
print(confusion_matrix(y_test, y_pred)) 

              precision    recall  f1-score   support

           0       0.11      0.07      0.09        14
           1       0.38      0.40      0.39        57
           2       0.18      0.26      0.21        35
           3       0.56      0.45      0.50        77

    accuracy                           0.37       183
   macro avg       0.31      0.30      0.30       183
weighted avg       0.40      0.37      0.38       183



[[ 1  6  5  2]
 [ 5 23 15 14]
 [ 3 11  9 12]
 [ 0 20 22 35]]


In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.datasets import make_blobs
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier

In [ ]:
clp = DecisionTreeClassifier(max_depth=None, min_samples_split=2, random_state=42)
clp.fit(X_train, y_train)
y_pred = clp.predict(X_test)
print(classification_report(y_test,y_pred))
print('\n')
print(confusion_matrix(y_test, y_pred)) 



              precision    recall  f1-score   support

           0       0.15      0.14      0.15        14
           1       0.45      0.42      0.44        57
           2       0.12      0.20      0.15        35
           3       0.49      0.39      0.43        77

    accuracy                           0.34       183
   macro avg       0.31      0.29      0.29       183
weighted avg       0.38      0.34      0.36       183



[[ 2  5  4  3]
 [ 5 24 15 13]
 [ 3 10  7 15]
 [ 3 14 30 30]]


In [ ]:
clf = RandomForestClassifier(n_estimators=10, max_depth=None,
min_samples_split=2, random_state=42)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(classification_report(y_test,y_pred))
print('\n')
print(confusion_matrix(y_test, y_pred)) 

scores = cross_val_score(clf, X, y, cv=5)
scores.mean()

              precision    recall  f1-score   support

           0       0.22      0.14      0.17        14
           1       0.43      0.40      0.41        57
           2       0.22      0.34      0.27        35
           3       0.56      0.48      0.52        77

    accuracy                           0.40       183
   macro avg       0.36      0.34      0.34       183
weighted avg       0.43      0.40      0.41       183



[[ 2  6  3  3]
 [ 3 23 15 16]
 [ 2 11 12 10]
 [ 2 14 24 37]]


0.3128091728091728

** Logistic Regression   XGB Classifier**

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import log_loss
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.ensemble import VotingClassifier

dataset.keys()

Index(['age', 'everused_alcohol', 'seen_pychaitrist', 'Depression', 'Anxiety',
       'Mental_Wellbeing', 'Somatic', 'NonSomatic_Somatic', 'Suicide'],
      dtype='object')

In [ ]:
y = dataset['Suicide']
X = dataset.drop(['Suicide'], axis=1)

In [ ]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

# initializing all the model objects with default parameters
model_1 = LogisticRegression()
model_2 = XGBClassifier()
model_3 = RandomForestClassifier()




In [ ]:
# Making the final model using voting classifier
final_model = VotingClassifier(estimators=[('lr', model_1), ('xgb', model_2), ('rf', model_3)], voting='hard')
 
# training all the model on the train dataset
final_model.fit(X_train, y_train)

 
# predicting the output on the test dataset
pred_final = final_model.predict(X_test)

#y_pred = clf.predict(X_test)
print(classification_report(y_test,pred_final))
print('\n')
print(confusion_matrix(y_test, pred_final)) 




/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


              precision    recall  f1-score   support

           0       0.74      0.96      0.84        76
           1       0.00      0.00      0.00        12
           2       0.54      0.30      0.39        23

    accuracy                           0.72       111
   macro avg       0.43      0.42      0.41       111
weighted avg       0.62      0.72      0.66       111



[[73  0  3]
 [ 9  0  3]
 [16  0  7]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
